# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bebd06a24f3d63a4236b6916ee41424099d6e969938d40b4ac9d357ae1a5e1cefb1f3a65bce6b65ab5acb9d0f2818e6728c358d7d46920e7ce02852a1e937de0

test:
  secret_key_base: 8e3f4e50081fe3fbf724d995af4c9da8a6712a113f38650611740f2a81a9aec4708a0e64ae635c44a6afc70adbb3b92534839e36bac724e713fac0b7bf985573

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
